<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="20898" started-at="2020-01-10T09:38:25Z" finished-at="2020-01-10T09:38:46Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="20898" started-at="2020-01-10T09:38:25Z" finished-at="2020-01-10T09:38:46Z">
      <class name="techM.TechMRunnerClass">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:techM.TechMRunnerClass@3712b94]" name="beforeSuite" is-config="true" duration-ms="200" started-at="2020-01-10T15:08:25Z" finished-at="2020-01-10T15:08:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="setUpClass()[pri:0, instance:techM.TechMRunnerClass@3712b94]" name="setUpClass" is-config="true" duration-ms="623" started-at="2020-01-10T15:08:25Z" finished-at="2020-01-10T15:08:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="FAIL" signature="feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:techM.TechMRunnerClass@3712b94]" name="feature" duration-ms="20150" started-at="2020-01-10T15:08:26Z" data-provider="features" finished-at="2020-01-10T15:08:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[End-To-End Scenario of customer creation, Account creation, Private customer creation, Buy & Execute the order.]]>
              </value>
            </param>
          </params>
          <exception class="cucumber.runtime.CucumberException">
            <message>
              <![CDATA[java.lang.NullPointerException]]>
            </message>
            <full-stacktrace>
              <![CDATA[cucumber.runtime.CucumberException: java.lang.NullPointerException
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at techM.TechMRunnerClass.feature(TechMRunnerClass.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.NullPointerException
	at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:69)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
	at com.sun.proxy.$Proxy23.clear(Unknown Source)
	at utilities.GenericWrapper.enterInputText(GenericWrapper.java:97)
	at pages.T24_SignInPage.enterUserName(T24_SignInPage.java:42)
	at stepdefinitions.T24_SignIn_Glue.i_sign_in_with_user(T24_SignIn_Glue.java:188)
	at âœ½.When I sign in with "adminUser" user(E2E_LoanWorkFlow.feature:11)
]]>
            </full-stacktrace>
          </exception> <!-- cucumber.runtime.CucumberException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- feature -->
        <test-method status="PASS" signature="tearDownClass()[pri:0, instance:techM.TechMRunnerClass@3712b94]" name="tearDownClass" is-config="true" duration-ms="4" started-at="2020-01-10T15:08:46Z" finished-at="2020-01-10T15:08:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:techM.TechMRunnerClass@3712b94]" name="afterSuite" is-config="true" duration-ms="338" started-at="2020-01-10T15:08:46Z" finished-at="2020-01-10T15:08:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- techM.TechMRunnerClass -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
